issue-#25: EEPROM data is validated and sanitized
Ensure the data stored in EEPROM is somewhat sanitized and within the
expected range. If not, the data is overwritten with default fallback
values.

Writing EEPROM data will warn about possible consequences and needs
response before proceeding. Optionally the current EEPROM content is
read back and stored to a file.

diff --git a/firmware/Makefile b/firmware/Makefile
--- a/firmware/Makefile
+++ b/firmware/Makefile
@@ -1,7 +1,7 @@
 #
 # 4chord MIDI - Makefile
 #
-# Copyright (C) 2017 Sven Gregori <sven@craplab.fi>
+# Copyright (C) 2018 Sven Gregori <sven@craplab.fi>
 #
 # This program is free software: you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -17,6 +17,7 @@
 #
 
 PROGRAM = 4chordmidi
+EEPROM_FILE = $(PROGRAM).eep
 
 OBJS  = main.o graphics.o spi.o uart.o lcd.o nokia_gfx.o buttons.o gui.o menu.o playback.o usb.o timer.o cli.o fonts.o eeprom.o
 OBJS += usbdrv/usbdrv.o usbdrv/usbdrvasm.o
@@ -24,7 +25,7 @@ OBJS += playback_mode_chord.o playback_mode_chord_arpeggio.o playback_mode_chord
 
 include ../common.mk
 
-cli.o: CFLAGS += -DBUILD_DATE_STRING="\"$(shell /bin/date +%d%m%y-%H%M%S)\""
+cli.o: CFLAGS += -DBUILD_DATE_STRING="\"$(shell /bin/date +%Y%m%d-%H%M%S)\""
 
 default: $(PROGRAM).hex $(PROGRAM).bin
 
@@ -32,25 +33,69 @@ $(PROGRAM).bin: $(PROGRAM).elf
 	@echo "[CP]  $@"
 	@$(OBJCOPY) -O binary -R .eeprom $< $@
 
-$(PROGRAM).eep: $(PROGRAM).elf
-	@echo "[CP]  $@"
-	@$(OBJCOPY) -j .eeprom --set-section-flags=.eeprom="alloc,load" --change-section-lma .eeprom=0 -O ihex $< $@
-
-program:
-	@echo "\n  +---------------------------------------------------+"
+program: $(PROGRAM).hex
+	@echo ""
+	@echo "  +---------------------------------------------------+"
 	@echo "  |                      WARNING                      |"
 	@echo "  | Flashing 4chord MIDI firmware WITHOUT bootloader! |"
-	@echo "  +---------------------------------------------------+\n"
+	@echo "  +---------------------------------------------------+"
+	@echo ""
 	$(AVRDUDE) $(AVRDUDE_FLAGS) -U flash:w:$(PROGRAM).hex
 
-program-eeprom: $(PROGRAM).eep
-	$(AVRDUDE) $(AVRDUDE_FLAGS) -U eeprom:w:$<
+
+eeprom: $(EEPROM_FILE)
+
+$(EEPROM_FILE): $(PROGRAM).elf
+	@echo "[CP]  $@.bin"
+	@$(OBJCOPY) -j .eeprom --set-section-flags=.eeprom="alloc,load" --change-section-lma .eeprom=0 -O binary $< $@.bin
+	@echo "[CP]  $@"
+	@$(OBJCOPY) -O ihex -I binary $@.bin $@
+
+program-eeprom: eeprom
+	@echo ""
+	@echo "  +-----------------------------------------------------+"
+	@echo "  |                       WARNING                       |"
+	@echo "  |                                                     |"
+	@echo "  |  You are about to overwrite the EEPROM content and  |"
+	@echo "  |  replace all existing values with your own custom   |"
+	@echo "  |  data, which may result in your device starting to  |"
+	@echo "  |  act funny, or fallback mechanisms in the firmware  |"
+	@echo "  |  might corrupt your custom data.                    |"
+	@echo "  |                                                     |"
+	@echo "  |  PROCEED AT OWN RISK!                               |"
+	@echo "  |                                                     |"
+	@echo "  +-----------------------------------------------------+"
+	@echo ""
+	@read -p "Are you sure you want to replace the EEPROM content? [y/N] " choice; \
+	[ "$${choice,,}" == "y" ] || (\
+		echo "Aborting"; \
+		exit 1; \
+	)
+	@read -p "Would you like to backup the current EEPROM content? [Y/n] " choice; \
+	[ "$${choice,,}" == "n" ] || (\
+		outfile="4chordmidi-$$(/bin/date +%Y-%m-%d-%H%M%S).eep"; \
+		echo -e "\nReading back EEPROM content to\n    $$outfile"; \
+		$(AVRDUDE) $(AVRDUDE_FLAGS) -U eeprom:r:$$outfile:i || exit 1; \
+	)
+	@echo -e "\nWriting new EEPROM data\n"
+	$(AVRDUDE) $(AVRDUDE_FLAGS) -U eeprom:w:$(EEPROM_FILE)
+	@echo ""
+	@echo "  +-----------------------------------------------------+"
+	@echo "  |                                                     |"
+	@echo "  |  All done.                                          |"
+	@echo "  |                                                     |"
+	@echo "  |  To ensure proper operation, make sure your EEPROM  |"
+	@echo "  |  data is always in sync with the firmware that is   |"
+	@echo "  |  accessing and validating the data itself.          |"
+	@echo "  |                                                     |"
+	@echo "  +-----------------------------------------------------+"
+	@echo ""
 
 distclean::
 	@echo "[RM]  $(PROGRAM).bin"
 	@rm -f $(PROGRAM).bin
-	@echo "[RM]  $(PROGRAM).eep"
-	@rm -f $(PROGRAM).eep
+	@echo "[RM]  $(EEPROM_FILE) $(EEPROM_FILE).bin"
+	@rm -f $(EEPROM_FILE) $(EEPROM_FILE).bin
 
-.PHONY: program program-eeprom distclean
+.PHONY: program eeprom program-eeprom distclean
 
